import type { CompositionState, Quad } from '../types';
export const DEFAULT_QUAD: Quad = [
  { x: 138 / 700, y: 113 / 525 },
  { x: 569 / 700, y: 113 / 525 },
  { x: 569 / 700, y: 355 / 525 },
  { x: 138 / 700, y: 355 / 525 },
];
export const createDefaults = (): CompositionState => ({
  name: 'Studio Display · Untitled',
  screen: {
    id: 'screen-1',
    name: 'Studio Display Screen',
    enabled: true,
    quad: structuredClone(DEFAULT_QUAD),
    inset: 0,
    radius: 0,
    opacity: 1,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    reflection: 0,
    blend: 'source-over',
  },
  designFit: 'width',
  extraScreens: [],
  designScale: 1,
  scrollY: 0,
  motion: {
    mode: 'cinematic',
    speed: 180,
    direction: 'down',
    duration: 12,
    delay: 1,
    endHold: 1.5,
    loop: false,
    easing: 'easeInOut',
    bezier: [0.42, 0, 0.58, 1],
    camera: 'none',
    keyframes: [
      { id: 'hero', time: 0, progress: 0, easing: 'linear' },
      { id: 'start', time: 1, progress: 0, easing: 'easeInOut' },
      { id: 'end', time: 10.5, progress: 1, easing: 'linear' },
      { id: 'hold', time: 12, progress: 1, easing: 'linear' },
    ],
  },
  output: {
    width: 3840,
    height: 2160,
    // The supplied 4:3 Studio Display stays fully visible inside the initial
    // 16:9 canvas, including the stand and desk rather than cropping its edges.
    framing: 'fit',
    scale: 1,
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
    background: 'original',
    color: '#747474',
    color2: '#333333',
  },
  screenshot: { format: 'png', quality: 0.95, scale: 1, filename: '' },
  video: {
    format: 'webm',
    width: 3840,
    height: 2160,
    fps: 30,
    bitrate: 60,
    duration: 12,
    codec: 'auto',
    mode: 'maximum',
  },
});
